from datetime import datetime
from fpdf import FPDF
from app.domain.schemas import DashboardOverviewResponse, DashboardAlertsResponse

class SustainabilityReport(FPDF):
    def header(self) -> None:
        self.set_font('helvetica', 'B', 15)
        self.cell(0, 10, 'SME Bridge Sustainability Summary', border=0, align='C', new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', align='C')

def generate_sustainability_summary_pdf(
    sme_name: str, 
    overview: DashboardOverviewResponse, 
    alerts: DashboardAlertsResponse
) -> bytes:
    """
    Generates a PDF summary report for an SME.
    """
    pdf = SustainabilityReport()
    pdf.add_page()
    pdf.set_font('helvetica', '', 12)
    
    # SME Info
    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 10, f'Organization: {sme_name}', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('helvetica', '', 10)
    pdf.cell(0, 10, f'Report Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    
    # Total CO2e
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Carbon Footprint Summary (YTD)', new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.set_font('helvetica', '', 11)
    pdf.cell(0, 10, f'Total Scope 3 Emissions: {overview.total_co2e_ytd:.2f} kg CO2e', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # Breakdown
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Category Breakdown', new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.set_font('helvetica', '', 11)
    pdf.cell(0, 10, f'- Electricity: {overview.electricity_co2e:.2f} kg CO2e', new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f'- Water: {overview.water_co2e:.2f} kg CO2e', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    
    # Data Quality
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Data Integrity & Review Status', new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.set_font('helvetica', '', 11)
    pdf.cell(0, 10, f'- Flagged for Review (Low Confidence): {alerts.flagged_low_confidence_count}', new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f'- Unreadable / Failed Extraction: {alerts.flagged_unreadable_count}', new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f'- Total Requiring Attention: {alerts.total_requiring_review}', new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(20)
    pdf.set_font('helvetica', 'I', 10)
    pdf.multi_cell(0, 10, 'This report was automatically generated by SME Bridge based on validated utility bill data and hardcoded Malaysian Grid Emission Factors.')

    return bytes(pdf.output())
